# https://grafana.com/docs/grafana-cloud/monitor-applications/application-observability/collector/opentelemetry-collector/
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        include_metadata: true
        endpoint: 0.0.0.0:4318

  prometheus/collector:
    config:
      scrape_configs:
        - job_name: "opentelemetry-collector"
          scrape_interval: 10s
          static_configs:
            - targets: [ ":8888" ]

  host_metric:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      load:
      network:

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  otlphttp/grafana:
    endpoint: https://logs-prod-012.grafana.net/otlp
    headers:
      Authorization: "Bearer ${GRAFANA_CLOUD_API_KEY}"

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/grafana
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/grafana
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/grafana
    metrics/collector:
      receivers:
        - prometheus/collector
        - host_metric
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/grafana

  telemetry:
    metrics:
      address: 0.0.0.0:8888
    logs:
      level: info